# Generated by Django 5.0.7 on 2024-12-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='profile_image',
            field=models.ImageField(default='profile_images/avatar.png', upload_to='profile_images/'),
        ),
    ]
