# Generated by Django 3.1.5 on 2024-12-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news_images/default_image.png', upload_to='news_images/'),
        ),
    ]
